##################################################
# file: EVSWSQueryService_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      /usr/bin/cacore2py
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from EVSWSQueryService_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
_queryRequest1Typecode = Struct(pname=("http://webservice.system.nci.nih.gov","query"), ofwhat=[ZSI.TC.String(pname="methodName", aname="_methodName", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.AnyType(pname="criteria", aname="_criteria", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://webservice.system.nci.nih.gov")
class queryRequest1:
    typecode = _queryRequest1Typecode
    __metaclass__ = pyclass_type
    def __init__(self, **kw):
        """Keyword parameters:
        methodName -- part methodName
        criteria -- part criteria
        """
        self._methodName =  kw.get("methodName")
        self._criteria =  kw.get("criteria")
queryRequest1.typecode.pyclass = queryRequest1

_queryResponse1Typecode = Struct(pname=("http://webservice.system.nci.nih.gov","queryResponse"), ofwhat=[ns0.ArrayOf_xsd_anyType_Def(pname="queryReturn", aname="_queryReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://webservice.system.nci.nih.gov")
class queryResponse1:
    typecode = _queryResponse1Typecode
    __metaclass__ = pyclass_type
    def __init__(self, **kw):
        """Keyword parameters:
        queryReturn -- part queryReturn
        """
        self._queryReturn =  kw.get("queryReturn")
queryResponse1.typecode.pyclass = queryResponse1

_queryRequest1Typecode = Struct(pname=("http://webservice.system.nci.nih.gov","query"), ofwhat=[ZSI.TC.String(pname="methodName", aname="_methodName", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.AnyType(pname="criteria", aname="_criteria", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://webservice.system.nci.nih.gov")
class queryRequest1:
    typecode = _queryRequest1Typecode
    __metaclass__ = pyclass_type
    def __init__(self, **kw):
        """Keyword parameters:
        methodName -- part methodName
        criteria -- part criteria
        """
        self._methodName =  kw.get("methodName")
        self._criteria =  kw.get("criteria")
queryRequest1.typecode.pyclass = queryRequest1

_queryResponse1Typecode = Struct(pname=("http://webservice.system.nci.nih.gov","queryResponse"), ofwhat=[ns0.ArrayOf_xsd_anyType_Def(pname="queryReturn", aname="_queryReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://webservice.system.nci.nih.gov")
class queryResponse1:
    typecode = _queryResponse1Typecode
    __metaclass__ = pyclass_type
    def __init__(self, **kw):
        """Keyword parameters:
        queryReturn -- part queryReturn
        """
        self._queryReturn =  kw.get("queryReturn")
queryResponse1.typecode.pyclass = queryResponse1

_queryObjectRequestTypecode = Struct(pname=("http://webservice.system.nci.nih.gov","queryObject"), ofwhat=[ZSI.TC.String(pname="targetClassName", aname="_targetClassName", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.AnyType(pname="criteria", aname="_criteria", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://webservice.system.nci.nih.gov")
class queryObjectRequest:
    typecode = _queryObjectRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self, **kw):
        """Keyword parameters:
        targetClassName -- part targetClassName
        criteria -- part criteria
        """
        self._targetClassName =  kw.get("targetClassName")
        self._criteria =  kw.get("criteria")
queryObjectRequest.typecode.pyclass = queryObjectRequest

_queryObjectResponseTypecode = Struct(pname=("http://webservice.system.nci.nih.gov","queryObjectResponse"), ofwhat=[ns0.ArrayOf_xsd_anyType_Def(pname="queryObjectReturn", aname="_queryObjectReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://webservice.system.nci.nih.gov")
class queryObjectResponse:
    typecode = _queryObjectResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self, **kw):
        """Keyword parameters:
        queryObjectReturn -- part queryObjectReturn
        """
        self._queryObjectReturn =  kw.get("queryObjectReturn")
queryObjectResponse.typecode.pyclass = queryObjectResponse


# Service Skeletons
class EVSWSQueryService(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='/evsapi41/services/evsapi41Service', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_query(self, ps, **kw):
        request = ps.Parse(queryRequest1.typecode)
        return request,queryResponse1()

    soapAction[''] = 'soap_query'
    root[(queryRequest1.typecode.nspname,queryRequest1.typecode.pname)] = 'soap_query'

    def soap_query(self, ps, **kw):
        request = ps.Parse(queryRequest1.typecode)
        return request,queryResponse1()

    soapAction[''] = 'soap_query'
    root[(queryRequest1.typecode.nspname,queryRequest1.typecode.pname)] = 'soap_query'

    def soap_queryObject(self, ps, **kw):
        request = ps.Parse(queryObjectRequest.typecode)
        return request,queryObjectResponse()

    soapAction[''] = 'soap_queryObject'
    root[(queryObjectRequest.typecode.nspname,queryObjectRequest.typecode.pname)] = 'soap_queryObject'

